export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  AUTHORIZATION_SUCCESS: 'AUTHORIZATION_SUCCESS',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  RETURN_INITIAL_STATE: 'RETURN_INITIAL_STATE',
  PERSONAL_DATA_SUCCESS: 'PERSONAL_DATA_SUCCESS',
  PERSONAL_DATA_ERROR: 'PERSONAL_DATA_ERROR',
  PERSONAL_DATA_REQUEST: 'PERSONAL_DATA_REQUEST',
};

export const alertConstants = {
  SUCCESS_ALERT: 'SUCCESS_ALERT',
  ERROR_ALERT: 'ERROR_ALERT',
  RESET_ALERT: 'RESET_ALERT',
};

export const registerConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  CONFIRM_REGISTER_SUCCESS: 'CONFIRM_REGISTER_SUCCESS',
  CONFIRM_REGISTER_ERROR: 'CONFIRM_REGISTER_ERROR',
  RETURN_INITIAL_STATE: 'RETURN_INITIAL_STATE',
};

export const basketConstants = {
  GET_BASKET: 'GET_BASKET',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  COUNT_PRODUCTS_AND_PRICE: 'COUNT_PRODUCTS_AND_PRICE',
  INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
  DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
  RESET: 'RESET',
};
